### ISSUE TITLE
Labels/names of folders in the taskbar would be useful.

### ISSUE THREAD

**Issue by pzi123** [brondavies/TrayToolbar#25]
After adding folders each of them shows up in the taskbar without the name. I have some 6 clusters of nodes I need to navigate to and their names on the folders would be very useful.

**Comment by brondavies** [comment]
I agree. However, we are limited to icons in the system tray since this isn't a full replacement of the old feature. The best we can get is a tooltip on hover, which it already does.

Alternatively, you can customize the icon of each folder in the properties dialog of each folder so that you have a unique icon in the tray at least.

**Comment by pzi123** [comment]
> I agree. However, we are limited to icons in the system tray since this isn't a full replacement of the old feature. The best we can get is a tooltip on hover, which it already does.
> 
> Alternatively, you can customize the icon of each folder in the properties dialog of each folder so that you have a unique icon in the tray at least.

Even with the same icon it is big help - thanks again. Changing the icon is quite elaborate and requires the restart of TrayToolbar. I think the solution is to give Microsoft enough feedback so they re-add the feature and promote their UX architect so he does not do any more damage.
